{
 "title": "Deribit vol analytics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "asset", "query": "btc, eth" }
  ]
 },
 "panels": [
  {
   "title": "ETH vs BTC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "ETH vs BTC 25C 1M",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25C\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "ETH vs BTC ATM 1M",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "ETH vs BTC 25P 1M",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25P\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "ETH vs BTC 25C 3M",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25C\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "ETH vs BTC ATM 3M",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "ETH vs BTC 25P 3M",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25P\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "ETH vs BTC ATM 6M",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"6M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "ETH vs BTC ATM 1Y",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1Y\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  { "title": "Risk reversal ($asset)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Risk reversal 25D 1M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 15D 1M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"15\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 25D 3M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 15D 3M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"15\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 25D 6M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"6M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 15D 6M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"15\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"6M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 25D 1Y",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1Y\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 5D 3M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"5\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}