{
 "title": "Deribit vol analytics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "asset", "query": "btc, eth" }
  ]
 },
 "panels": [
  { "title": "Smiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ETH Dec23 1600 vs 1200p 1x2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"eth_deribit_order_book\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"order_book\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /iv/)\r\n  |> filter(fn: (r) => r[\"instrument_name\"] == \"ETH-29DEC23-1600-P\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"eth_deribit_order_book\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"order_book\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /iv/)\r\n  |> filter(fn: (r) => r[\"instrument_name\"] == \"ETH-29DEC23-1200-P\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC Nov23 25/23p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"btc_deribit_order_book\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"order_book\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /iv/)\r\n  |> filter(fn: (r) => r[\"instrument_name\"] == \"BTC-24NOV23-25000-P\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"btc_deribit_order_book\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"order_book\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /iv/)\r\n  |> filter(fn: (r) => r[\"instrument_name\"] == \"BTC-24NOV23-23000-P\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 1M wings vs ATM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC Jun24 45/22rr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"btc_deribit_order_book\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"order_book\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /iv/)\r\n  |> filter(fn: (r) => r[\"instrument_name\"] == \"BTC-28JUN24-45000-C\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"btc_deribit_order_book\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"order_book\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /iv/)\r\n  |> filter(fn: (r) => r[\"instrument_name\"] == \"BTC-28JUN24-22000-P\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 3M wings vs ATM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 1M wings vs ATM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 6M wings vs ATM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"6M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"6M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 3M wings vs ATM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 6M wings vs ATM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"6M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"6M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Outright vols by tenor and delta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "BTC 1W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"7D\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 1W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"7D\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 2W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"2W\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 2W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"2W\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 1M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 1M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 2M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"2M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 2M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"2M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 3M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 3M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 6M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"6M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 6M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"6M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 1Y",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "query": "  from(bucket: \"btc_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1Y\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 1Y",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "query": "  from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1Y\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Outright vols by maturity and delta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 }
  },
  {
   "title": "BTC 28Jun24",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "query": "from(bucket: \"btc_vol_surfaces\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"expiry\"] == \"2024-06-28\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 25Aug23",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_surfaces\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"expiry\"] == \"2023-08-25\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 29Sep23",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "query": "from(bucket: \"btc_vol_surfaces\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"expiry\"] == \"2023-09-29\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 29Sep23",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_surfaces\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"expiry\"] == \"2023-09-29\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 27Oct23",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "query": "from(bucket: \"btc_vol_surfaces\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"expiry\"] == \"2023-10-27\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 27Oct23",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_surfaces\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"expiry\"] == \"2023-10-27\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 29Dec23",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "query": "from(bucket: \"btc_vol_surfaces\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"expiry\"] == \"2023-12-29\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 29Dec23",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_surfaces\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"expiry\"] == \"2023-12-29\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 29Mar24",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "targets": [
    {
     "query": "from(bucket: \"btc_vol_surfaces\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"expiry\"] == \"2024-03-29\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 29Mar24",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_surfaces\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"expiry\"] == \"2024-03-29\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTC 28Jun24",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "targets": [
    {
     "query": "from(bucket: \"btc_vol_surfaces\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"expiry\"] == \"2024-06-28\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH 28Jun24",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_surfaces\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volatility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mid_iv\")\r\n  |> filter(fn: (r) => r[\"delta\"] =~ /(10P|25P|ATM|25C|10C)$/)\r\n  |> filter(fn: (r) => r[\"expiry\"] == \"2024-06-28\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "ETH vs BTC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "ETH vs BTC 29Sep23 1900/30000",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "targets": [
    {
     "query": "from(bucket: \"btc_deribit_order_book\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"order_book\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /iv/)\r\n  |> filter(fn: (r) => r[\"instrument_name\"] == \"BTC-29SEP23-30000-C\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"eth_deribit_order_book\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"order_book\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /iv/)\r\n  |> filter(fn: (r) => r[\"instrument_name\"] == \"ETH-29SEP23-1900-C\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH vs BTC 29Sep23 1700/27000",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "targets": [
    {
     "query": "from(bucket: \"btc_deribit_order_book\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"order_book\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /iv/)\r\n  |> filter(fn: (r) => r[\"instrument_name\"] == \"BTC-29SEP23-26000-C\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"eth_deribit_order_book\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"order_book\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /iv/)\r\n  |> filter(fn: (r) => r[\"instrument_name\"] == \"ETH-29SEP23-1700-C\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH vs BTC 29Dec23 1600/26000 puts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "targets": [
    {
     "query": "from(bucket: \"btc_deribit_order_book\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"order_book\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /iv/)\r\n  |> filter(fn: (r) => r[\"instrument_name\"] == \"BTC-29DEC23-26000-P\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"eth_deribit_order_book\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"order_book\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /iv/)\r\n  |> filter(fn: (r) => r[\"instrument_name\"] == \"ETH-29DEC23-1600-P\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH vs BTC ATM 1M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH vs BTC 25C 1M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25C\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH vs BTC 25C 3M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25C\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH vs BTC 25P 1M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25P\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH vs BTC 25P 3M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25P\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH vs BTC ATM 3M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH vs BTC ATM 1Y",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1Y\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH vs BTC ATM 6M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "targets": [
    {
     "query": "from(bucket: \"eth_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eth_vs_btc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lower\" or r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"ATM\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"6M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Risk reversal ($asset)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 } },
  {
   "title": "Risk reversal 25D 1M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 197 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 15D 1M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 197 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"15\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 25D 3M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 206 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 15D 3M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 206 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"15\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 25D 6M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 215 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"6M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 15D 6M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 215 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"15\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"6M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 25D 1Y",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 224 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"25\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"1Y\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Risk reversal 5D 3M",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 224 },
   "targets": [
    {
     "query": "from(bucket: \"${asset}_vol_analytics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"risk_reversal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mavg\" or r[\"_field\"] == \"upper\" or r[\"_field\"] == \"value\" or r[\"_field\"] == \"lower\")\r\n  |> filter(fn: (r) => r[\"delta\"] == \"5\")\r\n  |> filter(fn: (r) => r[\"tenor\"] == \"3M\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}